[project]
name = "qradar-restapi-kafka-datapipeline"
version = "0.1.0"
description = ""
authors = [{ name = "Vikramaditya Tatke", email = "vtatke@securityhq.com" }]
requires-python = "~=3.11"
readme = "README.md"
dependencies = [
    "requests>=2.32.3,<3",
    "pydantic-settings>=2.3.4,<3",
    "loguru>=0.7.2,<0.8",
    "orjson>=3.10.0,<4",
    "ijson>=3.3.0,<4",
    "tenacity>=8.4.2,<9",
    "urllib3>=2.2.2,<3",
    "polars>=0.20.31,<0.21",
    "clickhouse-driver>=0.2.8,<0.3",
    "clickhouse-connect>=0.8.6,<0.9",
    "python-dateutil>=2.9.0.post0,<3",
]

[dependency-groups]
dev = [
    "black>=24.4.2,<25",
    "pylint>=3.2.5,<4",
    "jupyter>=1.1.1,<2",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.pyright]
venvPath = "."
venv = ".venv"
